# Generated by Django 5.0.6 on 2024-06-27 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationmodel',
            old_name='expiration_date',
            new_name='expiration_time',
        ),
        migrations.AddField(
            model_name='confirmationmodel',
            name='code',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
